version: '3'


services:
  # Nginx Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm:/data
      - npm:/etc/letsencrypt

    networks:
      - game_node_app

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 9443:9443

    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always


networks:
  game_node_app:
    external: true

volumes:
  # Nginx Proxy Manager
  npm:

  portainer:

