version: '3'


services:
  # Nginx Proxy Manager
  npm:
    hostname: npm
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm:/data
      - npm:/etc/letsencrypt

    networks:
      - game_node_app

networks:
  game_node_app:
    external: true

volumes:
  npm:

